# Generated by Django 4.2.5 on 2023-09-13 14:05

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(default=core.models.generate_unique_code, max_length=6, unique=True)),
                ('is_over', models.BooleanField(default=False)),
                ('o_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_games', to=settings.AUTH_USER_MODEL)),
                ('x_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
