# Generated by Django 4.2.5 on 2023-09-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_friend_game',
            field=models.BooleanField(default=False),
        ),
    ]
