# Generated by Django 4.2.4 on 2023-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
